### ISSUE TITLE
package configs

### ISSUE THREAD

**Issue by tampakrap** [smithfarm/dochazka#1]
We need to package the configs for both the server and the clients. If applicable, the perl tarball should provide a config .example, and the rpm should copy them to the appropriate place with the .example suffix

**Comment by smithfarm** [comment]
I agree this is a good idea. When the share dir is scanned, App::CELL::Load will ignore files that end in `.example` so that will work. However, there are many, many config parameters and only a few of them are user-tweakable.

So, I need to go over the config parameters and make such an example config.

**Comment by smithfarm** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;EiTI79EZ&#x2F;15-provide-example-rest-config"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Provide example REST config</a>

**Comment by tampakrap** [comment]
missing new releases for -CLI and -WWW that include the example configs. The specfiles are done

**Comment by tampakrap** [comment]
all done
