### ISSUE TITLE
sync data from ldap

### ISSUE THREAD

**Issue by tampakrap** [smithfarm/dochazka#16]
I would like the following two features, enabled only when using the LDAP authentication:

1) disable "edit user data" on user settings page, and instead introduce a "sync" button that will sync the specific user's data from ldap. In non-LDAP auth environment, I suppose the edit option should be available
2) A scheduled task (or a doc on how to create one manually) that will sync the data of all users from LDAP (so I can run it every X hours)

**Comment by smithfarm** [comment]
Yes, good idea. I added a trello card for this.

**Comment by smithfarm** [comment]
I'm removing the wishlist label from the LDAP sync tasks #16 and #17 - this seems as good a task as any.

**Comment by smithfarm** [comment]
Regarding the "sync all users from LDAP" functionality, there are two ways it could work:
1. We could add an internal boolean property (called "ldap" or "sync") to the employee class. When an employee object is created via LDAP_AUTOCREATE, this property would be set to "true". Then, the cronjob could simply sync all employees for whom this property is true.
2. The cronjob could take a list of employee nicks and just sync them in a loop. If an employee was found in LDAP but not in Dochazka, it would be autocreated if LDAP_AUTOCREATE is true, otherwise it would just be logged. If an employee was found in Dochazka but not in LDAP, the employee's privlevel would be changed to "inactive" if LDAP_AUTODEACTIVATE is true.

Advantage of option 1 is the cronjob is very simple - just run a command with no arguments. Disadvantage is that employees have to be deactivated manually by HR.

Advantage of option 2 is that employees are deactivated automatically by LDAP sync. Makes life easier for HR. Disadvantage is HR has to maintain a separate list of active employees and the cronjob/script has to be able to process that list.

**Comment by smithfarm** [comment]
I'm leaning towards 1. HR will have Dochazka action items whenever employees enter or leave the company, no matter what. Option 1 keeps the script simple.

**Comment by tampakrap** [comment]
this is not what I asked for. I wanted to sync the email, sec_id (and other options) from ldap for the users that already exist in the dochazka db

**Comment by smithfarm** [comment]
The issue is: what to do about employees that are in Dochazka, but not in LDAP? Examples: "root" and "demo" (and admins may create others, too).

Anyway, option 1 it is!

**Comment by tampakrap** [comment]
understood, and I agree with option 1. Regarding user deactivation, it should be configurable as there are many options depending on the environment, eg:
1) user is not in ldap any more (perform an ldapsearch and see if the username exists)
2) there is a special attribute eg employeeActive
3) manually deactivate employees in dochazka, as the ldap doesn't indicate whether an employee is active or inactive

I am not sure how to handle username renames though.Probably we should ignore this for now, and discuss it on a separate ticket, after this one is fixed

**Comment by smithfarm** [comment]
Done in App::Dochazka::WWW version 0.141
