### ISSUE TITLE
WWW, CLI: hide EID and show the secondary ID via configurable title

### ISSUE THREAD

**Issue by tampakrap** [smithfarm/dochazka#17]
Under the user profile a user can see his EID, but this information is useless and confusing. Instead, it would be good to show up the sec_id, via a configurable name, synced from a configurable LDAP attribute (which could be for example the employee's company LDAP ID).

https://metacpan.org/pod/App::Dochazka::REST::Guide#Employee

**Comment by smithfarm** [comment]
I disagree that it's useless. If an organization had no other unique numeric ID for its employees, it could use Dochazka EID. In that case, HR would tell employees about their EID and nobody would be confused :-)

But otherwise I agree that if there is a unique numeric ID coming from LDAP, it can be used in place of EID.

One other nitpick: in Dochazka terminology users are referred to as "employees".

**Comment by tampakrap** [comment]
agreed, so options are: don't expose it when sec_id is set up, or make it configurable if it will be exposed

**Comment by smithfarm** [comment]
For WWW I don't have a good way to make the name configurable right now, but the LDAP attribute is configurable and in the next release of WWW the employee profile will say "Workforce ID" instead of EID.

Next I will do CLI.

**Comment by smithfarm** [comment]
WWW: fixed by https://github.com/smithfarm/dochazka-www/commit/9e83d5a78c2a75ccdc90e0db69bad01450f2edcf
CLI: fixed by https://github.com/smithfarm/dochazka-cli/commit/a22e01c89c80406c052ec2f56beeeb40afdfe4de

**Comment by smithfarm** [comment]
Opened https://github.com/smithfarm/mfile-www/issues/11 to track the issue of passing config parameters to the JS side from a derived distro.
